# Generated by Django 2.2 on 2020-05-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prep_time', models.IntegerField(help_text='in minutes')),
                ('cook_time', models.IntegerField(help_text='in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
