# Generated by Django 3.1.4 on 2021-04-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255)),
                ('common_names', models.CharField(max_length=255)),
                ('edible_parts', models.CharField(max_length=255)),
                ('minZone', models.IntegerField(help_text='minimum USDA zone 1-9')),
                ('maxZone', models.IntegerField(help_text=' maximum USDA zone 1-9')),
                ('soil_types', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
