# Generated by Django 3.1.4 on 2021-08-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='drought_tolerance',
            field=models.CharField(blank=True, choices=[('a', 'All'), ('h', 'High'), ('f', 'Moderate'), ('l', 'Low')], default='a', help_text='help text', max_length=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='soil_types',
            field=models.CharField(blank=True, help_text='tolerates sand, tolerates clay, etc.', max_length=255),
        ),
    ]
