# Generated by Django 3.1.4 on 2021-08-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210807_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='costs',
            field=models.CharField(default='cook', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='water', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='procedure',
            field=models.TextField(default='cook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='tools',
            field=models.CharField(default='Instapot', max_length=255),
        ),
    ]
