# Generated by Django 3.1.4 on 2021-08-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20210807_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='retailers',
            field=models.CharField(default='James', max_length=255),
            preserve_default=False,
        ),
    ]
