# Generated by Django 3.1.4 on 2021-08-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20210810_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.URLField(default='exit'),
            preserve_default=False,
        ),
    ]
