# Generated by Django 3.1.4 on 2021-08-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_auto_20210810_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='screen_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
