# Generated by Django 3.1.4 on 2021-08-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_plant_screen_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='retailers',
        ),
        migrations.AddField(
            model_name='plant',
            name='retailers',
            field=models.ManyToManyField(to='myapi.Retailer'),
        ),
    ]
