# Generated by Django 3.1.4 on 2021-08-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_auto_20210810_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='link',
            field=models.URLField(default='www.facebook.com'),
            preserve_default=False,
        ),
    ]
