# Generated by Django 3.1.4 on 2021-08-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_retailer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='retailers',
            field=models.ManyToManyField(blank=True, to='myapi.Retailer'),
        ),
    ]
